version: 0.2

phases:
  install:
    commands:
      - echo "Instalando kubectl"
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - echo "Autenticando en EKS"
      - aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME

  build:
    commands:
      - echo "Desplegando en Kubernetes"
      - kubectl apply -f /path/to/kubernetes/deployment.yaml
      - kubectl apply -f /path/to/kubernetes/service.yaml
      - kubectl apply -f /path/to/kubernetes/ingress.yaml

artifacts:
  files:
    - "**/*"
